apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: eks-control-plane.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: EKSControlPlane
    spec:
      version: string | required=true description="Kubernetes version"
      vpc:
        subnetIDs: '[]string | required=true description="Subnet IDs"'
        securityGroupIDs: '[]string | default=[] description="Security group IDs"'

    status:
      endpoint: ${cluster.?status.?endpoint.orValue("")}
      ready: ${int(cluster.?status.?status.orValue("") == "ACTIVE" && cluster.?status.?endpoint.orValue("") != "") == 1}

  resources:
    - id: clusterRole
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Role
        metadata:
          name: ${schema.metadata.name}-eks-control-plane
        spec:
          name: ${schema.metadata.name}-eks-control-plane
          assumeRolePolicyDocument: |
            {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"eks.amazonaws.com"},"Action":"sts:AssumeRole"}]}

    - id: cluster
      template:
        apiVersion: eks.services.k8s.aws/v1alpha1
        kind: Cluster
        metadata:
          name: ${schema.metadata.name}
        spec:
          name: ${schema.metadata.name}
          version: ${schema.spec.version}
          roleARN: ${clusterRole.status.ackResourceMetadata.arn}
          resourcesVPCConfig:
            subnetIDs: ${schema.spec.vpc.subnetIDs}
            securityGroupIDs: ${schema.spec.vpc.securityGroupIDs}

      readyWhen:
        - ${cluster.?status.?status.orValue("") == "ACTIVE" && cluster.?status.?endpoint.orValue("") != ""}
