---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha1-kany8scontrolplane
  failurePolicy: Fail
  name: vkany8scontrolplane.kb.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kany8scontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha1-kany8scontrolplanetemplate
  failurePolicy: Fail
  name: vkany8scontrolplanetemplate.kb.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kany8scontrolplanetemplates
  sideEffects: None
