apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: demo-docker
  namespace: default
spec:
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: DockerCluster
    name: demo-docker
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: Kany8sControlPlane
    name: demo-docker
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: DockerCluster
metadata:
  name: demo-docker
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: Kany8sControlPlane
metadata:
  name: demo-docker
  namespace: default
spec:
  version: "1.29"
  resourceGraphDefinitionRef:
    name: docker-control-plane.kro.run
