---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kany8scontrolplanes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kany8scontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kany8scontrolplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kro.run
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kro.run
  resources:
  - resourcegraphdefinitions
  verbs:
  - get
  - list
  - watch
