apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: Kany8sClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: kany8s
    app.kubernetes.io/managed-by: kustomize
  name: demo-cluster-template
spec:
  template:
    spec:
      kroSpec: {}
