## Append samples of your project ##
resources:
- controlplane_v1alpha1_kany8scontrolplane.yaml
- controlplane_v1alpha1_kany8scontrolplanetemplate.yaml
- infrastructure_v1alpha1_kany8scluster.yaml
- infrastructure_v1alpha1_kany8sclustertemplate.yaml
- controlplane_v1alpha1_kany8skubeadmcontrolplane.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
