//go:build !ignore_autogenerated

/*
Copyright 2026.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/errors"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlane) DeepCopyInto(out *Kany8sControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlane.
func (in *Kany8sControlPlane) DeepCopy() *Kany8sControlPlane {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneInitializationStatus) DeepCopyInto(out *Kany8sControlPlaneInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneInitializationStatus.
func (in *Kany8sControlPlaneInitializationStatus) DeepCopy() *Kany8sControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneList) DeepCopyInto(out *Kany8sControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kany8sControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneList.
func (in *Kany8sControlPlaneList) DeepCopy() *Kany8sControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneSpec) DeepCopyInto(out *Kany8sControlPlaneSpec) {
	*out = *in
	out.ResourceGraphDefinitionRef = in.ResourceGraphDefinitionRef
	if in.KroSpec != nil {
		in, out := &in.KroSpec, &out.KroSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlaneEndpoint != nil {
		in, out := &in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint
		*out = new(v1beta1.APIEndpoint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneSpec.
func (in *Kany8sControlPlaneSpec) DeepCopy() *Kany8sControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneStatus) DeepCopyInto(out *Kany8sControlPlaneStatus) {
	*out = *in
	if in.Initialization != nil {
		in, out := &in.Initialization, &out.Initialization
		*out = new(Kany8sControlPlaneInitializationStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(errors.ClusterStatusError)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneStatus.
func (in *Kany8sControlPlaneStatus) DeepCopy() *Kany8sControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGraphDefinitionRef) DeepCopyInto(out *ResourceGraphDefinitionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGraphDefinitionRef.
func (in *ResourceGraphDefinitionRef) DeepCopy() *ResourceGraphDefinitionRef {
	if in == nil {
		return nil
	}
	out := new(ResourceGraphDefinitionRef)
	in.DeepCopyInto(out)
	return out
}
