//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplate) DeepCopyInto(out *Kany8sClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplate.
func (in *Kany8sClusterTemplate) DeepCopy() *Kany8sClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateList) DeepCopyInto(out *Kany8sClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kany8sClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateList.
func (in *Kany8sClusterTemplateList) DeepCopy() *Kany8sClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateResource) DeepCopyInto(out *Kany8sClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateResource.
func (in *Kany8sClusterTemplateResource) DeepCopy() *Kany8sClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateResourceSpec) DeepCopyInto(out *Kany8sClusterTemplateResourceSpec) {
	*out = *in
	if in.KroSpec != nil {
		in, out := &in.KroSpec, &out.KroSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateResourceSpec.
func (in *Kany8sClusterTemplateResourceSpec) DeepCopy() *Kany8sClusterTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateSpec) DeepCopyInto(out *Kany8sClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateSpec.
func (in *Kany8sClusterTemplateSpec) DeepCopy() *Kany8sClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlane) DeepCopyInto(out *Kany8sControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlane.
func (in *Kany8sControlPlane) DeepCopy() *Kany8sControlPlane {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneInitializationStatus) DeepCopyInto(out *Kany8sControlPlaneInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneInitializationStatus.
func (in *Kany8sControlPlaneInitializationStatus) DeepCopy() *Kany8sControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneList) DeepCopyInto(out *Kany8sControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kany8sControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneList.
func (in *Kany8sControlPlaneList) DeepCopy() *Kany8sControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneSpec) DeepCopyInto(out *Kany8sControlPlaneSpec) {
	*out = *in
	out.ResourceGraphDefinitionRef = in.ResourceGraphDefinitionRef
	if in.KroSpec != nil {
		in, out := &in.KroSpec, &out.KroSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneSpec.
func (in *Kany8sControlPlaneSpec) DeepCopy() *Kany8sControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneStatus) DeepCopyInto(out *Kany8sControlPlaneStatus) {
	*out = *in
	out.Initialization = in.Initialization
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneStatus.
func (in *Kany8sControlPlaneStatus) DeepCopy() *Kany8sControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneTemplate) DeepCopyInto(out *Kany8sControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneTemplate.
func (in *Kany8sControlPlaneTemplate) DeepCopy() *Kany8sControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneTemplateList) DeepCopyInto(out *Kany8sControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kany8sControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneTemplateList.
func (in *Kany8sControlPlaneTemplateList) DeepCopy() *Kany8sControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneTemplateResource) DeepCopyInto(out *Kany8sControlPlaneTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneTemplateResource.
func (in *Kany8sControlPlaneTemplateResource) DeepCopy() *Kany8sControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneTemplateResourceSpec) DeepCopyInto(out *Kany8sControlPlaneTemplateResourceSpec) {
	*out = *in
	out.ResourceGraphDefinitionRef = in.ResourceGraphDefinitionRef
	if in.KroSpec != nil {
		in, out := &in.KroSpec, &out.KroSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneTemplateResourceSpec.
func (in *Kany8sControlPlaneTemplateResourceSpec) DeepCopy() *Kany8sControlPlaneTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sControlPlaneTemplateSpec) DeepCopyInto(out *Kany8sControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sControlPlaneTemplateSpec.
func (in *Kany8sControlPlaneTemplateSpec) DeepCopy() *Kany8sControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGraphDefinitionReference) DeepCopyInto(out *ResourceGraphDefinitionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGraphDefinitionReference.
func (in *ResourceGraphDefinitionReference) DeepCopy() *ResourceGraphDefinitionReference {
	if in == nil {
		return nil
	}
	out := new(ResourceGraphDefinitionReference)
	in.DeepCopyInto(out)
	return out
}
