//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sCluster) DeepCopyInto(out *Kany8sCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sCluster.
func (in *Kany8sCluster) DeepCopy() *Kany8sCluster {
	if in == nil {
		return nil
	}
	out := new(Kany8sCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterInitializationStatus) DeepCopyInto(out *Kany8sClusterInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterInitializationStatus.
func (in *Kany8sClusterInitializationStatus) DeepCopy() *Kany8sClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterList) DeepCopyInto(out *Kany8sClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kany8sCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterList.
func (in *Kany8sClusterList) DeepCopy() *Kany8sClusterList {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterSpec) DeepCopyInto(out *Kany8sClusterSpec) {
	*out = *in
	if in.KroSpec != nil {
		in, out := &in.KroSpec, &out.KroSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterSpec.
func (in *Kany8sClusterSpec) DeepCopy() *Kany8sClusterSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterStatus) DeepCopyInto(out *Kany8sClusterStatus) {
	*out = *in
	out.Initialization = in.Initialization
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterStatus.
func (in *Kany8sClusterStatus) DeepCopy() *Kany8sClusterStatus {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplate) DeepCopyInto(out *Kany8sClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplate.
func (in *Kany8sClusterTemplate) DeepCopy() *Kany8sClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateList) DeepCopyInto(out *Kany8sClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kany8sClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateList.
func (in *Kany8sClusterTemplateList) DeepCopy() *Kany8sClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kany8sClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateResource) DeepCopyInto(out *Kany8sClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateResource.
func (in *Kany8sClusterTemplateResource) DeepCopy() *Kany8sClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateResourceSpec) DeepCopyInto(out *Kany8sClusterTemplateResourceSpec) {
	*out = *in
	if in.KroSpec != nil {
		in, out := &in.KroSpec, &out.KroSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateResourceSpec.
func (in *Kany8sClusterTemplateResourceSpec) DeepCopy() *Kany8sClusterTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kany8sClusterTemplateSpec) DeepCopyInto(out *Kany8sClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kany8sClusterTemplateSpec.
func (in *Kany8sClusterTemplateSpec) DeepCopy() *Kany8sClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(Kany8sClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGraphDefinitionReference) DeepCopyInto(out *ResourceGraphDefinitionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGraphDefinitionReference.
func (in *ResourceGraphDefinitionReference) DeepCopy() *ResourceGraphDefinitionReference {
	if in == nil {
		return nil
	}
	out := new(ResourceGraphDefinitionReference)
	in.DeepCopyInto(out)
	return out
}
