apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../eks-plugin
patches:
  - target:
      kind: Deployment
      name: eks-kubeconfig-rotator
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts
      - op: remove
        path: /spec/template/spec/volumes
