apiVersion: kro.run/v1alpha1
kind: Bucket
metadata:
  name: demo-bucket-aws
spec:
  provider: aws
  bucketName: my-company-demo-bucket-12345
  versioningEnabled: true
  aws:
    region: ap-northeast-1
    blockPublicAccess: true
    tags:
      - key: owner
        value: platform
      - key: env
        value: dev
